"""
Generate two 16x24 bitmap font tables for the TFT display: Consolas Bold + Regular.
Output: tft_font_modern.h — both tables in one file, selectable at runtime.

Strategy:
1. Render at 8x resolution (hi-res) for best quality
2. Apply Gaussian blur to smooth jagged edges symmetrically
3. Downscale to 16x24 using LANCZOS (high-quality resampling)
4. Threshold to 1-bit

Bit ordering: bit 0 = leftmost pixel, bit 15 = rightmost pixel.
Row ordering: glyph[0] = top row, glyph[23] = bottom row.
"""

import os
import sys

from PIL import Image, ImageDraw, ImageFilter, ImageFont

CELL_W = 16
CELL_H = 24
SCALE = 8
HI_H = CELL_H * SCALE  # 192
CHARS = [chr(c) for c in range(0x20, 0x7F)]  # 95 printable ASCII

VARIANTS = [
    {
        "name": "bold",
        "array": "tft_font_table_bold",
        "path": "C:/Windows/Fonts/consolab.ttf",
        "fallback": "C:/Windows/Fonts/consola.ttf",
        "size": 190,
        "blur": 2.5,
        "threshold": 95,
    },
    {
        "name": "regular",
        "array": "tft_font_table_regular",
        "path": "C:/Windows/Fonts/consola.ttf",
        "fallback": "C:/Windows/Fonts/lucon.ttf",
        "size": 190,
        "blur": 2.0,
        "threshold": 95,
    },
]

PREVIEW_CHARS = ['A', 'M', 'N', 'I', 'i', '.', 'g', ':', '0', 'W']


def load_font(primary, fallback, size):
    for p in [primary, fallback]:
        if os.path.exists(p):
            try:
                return ImageFont.truetype(p, size), os.path.basename(p)
            except OSError:
                continue
    return None, ""


def generate_glyphs(font, blur_sigma, threshold):
    ascent, descent = font.getmetrics()

    # Measure widest character
    max_w = 0
    for test_ch in 'MWN@#':
        bb = font.getbbox(test_ch)
        w = bb[2] - bb[0]
        max_w = max(max_w, w)

    # Canvas width: character fills ~93% of cell
    hi_w = int(max_w / 0.93)

    # Baseline: tiny top padding (4px hi-res) so blur doesn't clip the top edge
    cap_top_hi = 4
    baseline_y_hi = cap_top_hi + ascent

    all_glyphs = []
    for ch in CHARS:
        img_hi = Image.new('L', (hi_w, HI_H), 0)
        draw = ImageDraw.Draw(img_hi)

        bbox = draw.textbbox((0, 0), ch, font=font, anchor='ls')
        cw = bbox[2] - bbox[0]
        x_off = (hi_w - cw) / 2.0 - bbox[0]

        draw.text((x_off, baseline_y_hi), ch, fill=255, font=font, anchor='ls')

        # Gaussian blur for smooth, symmetric edges
        img_hi = img_hi.filter(ImageFilter.GaussianBlur(radius=blur_sigma))

        # Downscale to target cell size
        img_lo = img_hi.resize((CELL_W, CELL_H), Image.LANCZOS)

        # Convert to uint16 rows
        rows = []
        for r in range(CELL_H):
            val = 0
            for c in range(CELL_W):
                if img_lo.getpixel((c, r)) > threshold:
                    val |= (1 << c)
            rows.append(val)
        all_glyphs.append(rows)

    return all_glyphs, ascent, descent, max_w, hi_w


# ── Generate both variants ──
results = {}
for var in VARIANTS:
    font, fname = load_font(var["path"], var["fallback"], var["size"])
    if font is None:
        print(f"ERROR: no font found for {var['name']}")
        sys.exit(1)
    glyphs, asc, desc, adv_w, hi_w = generate_glyphs(
        font, var["blur"], var["threshold"]
    )
    results[var["name"]] = glyphs
    print(f"\n{var['name'].upper()}: {fname} size={var['size']} "
          f"blur={var['blur']} thresh={var['threshold']}")
    print(f"  ascent={asc} descent={desc} advance_w={adv_w} hi_w={hi_w}")

    # Preview
    print(f"\n  === {var['name']} Preview ===")
    for ch in PREVIEW_CHARS:
        idx = ord(ch) - 0x20
        print(f"\n  '{ch}' (0x{ord(ch):02X}):")
        for r in range(CELL_H):
            val = glyphs[idx][r]
            line = ''.join(
                '#' if (val & (1 << b)) else '.' for b in range(CELL_W)
            )
            print(f"    {line}  0x{val:04X}")

# ── Write combined C header ──
OUT_PATH = os.path.join(
    os.path.dirname(__file__), '..', 'Aurix_Firmware', 'tft_font_modern.h'
)
OUT_PATH = os.path.normpath(OUT_PATH)

lines = []
lines.append('#ifndef TFT_FONT_MODERN_H')
lines.append('#define TFT_FONT_MODERN_H')
lines.append('')
lines.append('/******************************************************************************')
lines.append(' * tft_font_modern.h -- 16x24 bitmap fonts: Consolas Bold + Regular')
lines.append(' *')
lines.append(' * ASCII characters 0x20 (space) through 0x7E (~).')
lines.append(' * Each character is 24 rows of 16-bit patterns (bit 0 = leftmost pixel).')
lines.append(' * Total per table: 95 characters x 24 = 2280 entries.')
lines.append(' *')
lines.append(' * Generated by scripts/gen_font.py -- do not edit manually.')
lines.append(' ******************************************************************************/')
lines.append('')
lines.append('#include "Ifx_Types.h"')
lines.append('')
lines.append('#ifdef __cplusplus')
lines.append('extern "C" {')
lines.append('#endif')

for var in VARIANTS:
    glyphs = results[var["name"]]
    lines.append('')
    weight = "Bold" if "bold" in var["name"] else "Regular"
    lines.append(f'/* {weight} weight -- Consolas {weight} */')
    lines.append(f'static const uint16 {var["array"]}[] =')
    lines.append('{')

    for i, ch in enumerate(CHARS):
        if ch == "'":
            label = "\\'"
        elif ch == '\\':
            label = "\\\\"
        else:
            label = ch
        lines.append(f"    /* '{label}' (0x{ord(ch):02X}) */")

        for j in range(0, CELL_H, 8):
            end = min(j + 8, CELL_H)
            vals = ', '.join(
                f'0x{glyphs[i][j + k]:04X}' for k in range(end - j)
            )
            lines.append(f'    {vals},')

    lines.append('};')

lines.append('')
lines.append('#ifdef __cplusplus')
lines.append('}')
lines.append('#endif')
lines.append('')
lines.append('#endif /* TFT_FONT_MODERN_H */')
lines.append('')

with open(OUT_PATH, 'w', newline='\n') as f:
    f.write('\n'.join(lines))

print(f"\nWritten {len(CHARS)} characters x 2 weights to {OUT_PATH}")
